# Configurações do site
title: </> Pedro
description: Olá, me chamo Pedro, sou desenvoledor de software e tenho 21 anos, nesse site compartilho ideias, projetos e minhas opiniões.
url: http://127.0.0.1:4000/ # URL do seu site
baseurl: "/" # Base URL do seu site (deixe como "/" se estiver na raiz do domínio)

# Configurações do tema
theme: meu-tema # Nome do diretório do seu tema Jekyll (se aplicável)

# Configurações do blog
permalink: /blog/:title # Estrutura de URL para os posts do blog
paginate: 5 # Número de posts por página na listagem do blog

# Configurações do Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Outras configurações
plugins:
  - jekyll
  # Outros plugins que você possa querer usar
